// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProblemReportingSystem.DAL.Infrastructure;

#nullable disable

namespace ProblemReportingSystem.DAL.Infrastructure.Migrations
{
    [DbContext(typeof(ProblemReportingSystemDbContext))]
    [Migration("20260416100109_TimeConvertion")]
    partial class TimeConvertion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("District")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("district");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Oblast")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oblast");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.HasKey("AddressId")
                        .HasName("addresses_pkey");

                    b.HasIndex(new[] { "Latitude", "Longitude" }, "idx_addresses_coordinates");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_level");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AdminId")
                        .HasName("admins_pkey");

                    b.HasIndex(new[] { "UserId" }, "admins_user_id_key")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Appeal", b =>
                {
                    b.Property<Guid>("AppealId")
                        .HasColumnType("uuid")
                        .HasColumnName("appeal_id");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_employee_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AppealId")
                        .HasName("appeals_pkey");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("appeals", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.CityCouncil", b =>
                {
                    b.Property<Guid>("CouncilId")
                        .HasColumnType("uuid")
                        .HasColumnName("council_id");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("CouncilId")
                        .HasName("city_councils_pkey");

                    b.HasIndex("AddressId");

                    b.ToTable("city_councils", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.CouncilEmployee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("CouncilId")
                        .HasColumnType("uuid")
                        .HasColumnName("council_id");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EmployeeId")
                        .HasName("council_employees_pkey");

                    b.HasIndex("CouncilId");

                    b.HasIndex(new[] { "UserId" }, "council_employees_user_id_key")
                        .IsUnique();

                    b.ToTable("council_employees", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Poll", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_id");

                    b.Property<Guid>("CouncilId")
                        .HasColumnType("uuid")
                        .HasColumnName("council_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("PollId")
                        .HasName("polls_pkey");

                    b.HasIndex("CouncilId");

                    b.HasIndex(new[] { "IsActive", "PublishedAt" }, "idx_polls_active");

                    b.ToTable("polls", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.PollOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("option_text");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_id");

                    b.HasKey("OptionId")
                        .HasName("poll_options_pkey");

                    b.HasIndex("PollId");

                    b.ToTable("poll_options", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.PollVote", b =>
                {
                    b.Property<Guid>("VoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("vote_id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("voted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("VoteId")
                        .HasName("poll_votes_pkey");

                    b.HasIndex("OptionId");

                    b.HasIndex(new[] { "UserId", "OptionId" }, "unique_user_vote")
                        .IsUnique();

                    b.ToTable("poll_votes", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("ProblemId")
                        .HasName("problems_pkey");

                    b.HasIndex("AddressId");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Status" }, "idx_problems_status");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.ProblemCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("problem_categories_pkey");

                    b.ToTable("problem_categories", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.ProblemPhoto", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("PhotoId")
                        .HasName("problem_photos_pkey");

                    b.HasIndex("ProblemId");

                    b.ToTable("problem_photos", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleAuthId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_auth_id");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "GoogleAuthId" }, "users_google_auth_id_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.VCouncilEfficiencyReport", b =>
                {
                    b.Property<Guid?>("CouncilId")
                        .HasColumnType("uuid")
                        .HasColumnName("council_id");

                    b.Property<string>("CouncilName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("council_name");

                    b.Property<decimal?>("EfficiencyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("efficiency_percentage");

                    b.Property<long?>("ResolvedAppeals")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_appeals");

                    b.Property<long?>("TotalAppeals")
                        .HasColumnType("bigint")
                        .HasColumnName("total_appeals");

                    b.ToTable((string)null);

                    b.ToView("v_council_efficiency_report", (string)null);
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Admin", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("ProblemReportingSystem.DAL.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("admins_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Appeal", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.CouncilEmployee", "AssignedEmployee")
                        .WithMany("Appeals")
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("appeals_assigned_employee_id_fkey");

                    b.HasOne("ProblemReportingSystem.DAL.Entities.Problem", "Problem")
                        .WithMany("Appeals")
                        .HasForeignKey("ProblemId")
                        .HasConstraintName("appeals_problem_id_fkey");

                    b.HasOne("ProblemReportingSystem.DAL.Entities.User", "User")
                        .WithMany("Appeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appeals_user_id_fkey");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.CityCouncil", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.Address", "Address")
                        .WithMany("CityCouncils")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("city_councils_address_id_fkey");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.CouncilEmployee", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.CityCouncil", "Council")
                        .WithMany("CouncilEmployees")
                        .HasForeignKey("CouncilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("council_employees_council_id_fkey");

                    b.HasOne("ProblemReportingSystem.DAL.Entities.User", "User")
                        .WithOne("CouncilEmployee")
                        .HasForeignKey("ProblemReportingSystem.DAL.Entities.CouncilEmployee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("council_employees_user_id_fkey");

                    b.Navigation("Council");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Poll", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.CityCouncil", "Council")
                        .WithMany("Polls")
                        .HasForeignKey("CouncilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("polls_council_id_fkey");

                    b.Navigation("Council");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.PollOption", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.Poll", "Poll")
                        .WithMany("PollOptions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("poll_options_poll_id_fkey");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.PollVote", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.PollOption", "Option")
                        .WithMany("PollVotes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("poll_votes_option_id_fkey");

                    b.HasOne("ProblemReportingSystem.DAL.Entities.User", "User")
                        .WithMany("PollVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("poll_votes_user_id_fkey");

                    b.Navigation("Option");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Problem", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.Address", "Address")
                        .WithMany("Problems")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("problems_address_id_fkey");

                    b.HasOne("ProblemReportingSystem.DAL.Entities.ProblemCategory", "Category")
                        .WithMany("Problems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("problems_category_id_fkey");

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.ProblemPhoto", b =>
                {
                    b.HasOne("ProblemReportingSystem.DAL.Entities.Problem", "Problem")
                        .WithMany("ProblemPhotos")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("problem_photos_problem_id_fkey");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Address", b =>
                {
                    b.Navigation("CityCouncils");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.CityCouncil", b =>
                {
                    b.Navigation("CouncilEmployees");

                    b.Navigation("Polls");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.CouncilEmployee", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Poll", b =>
                {
                    b.Navigation("PollOptions");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.PollOption", b =>
                {
                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.Problem", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("ProblemPhotos");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.ProblemCategory", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("ProblemReportingSystem.DAL.Entities.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Appeals");

                    b.Navigation("CouncilEmployee");

                    b.Navigation("PollVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
